### ISSUE TITLE
"Invalid path in host" error

### ISSUE THREAD

**Issue by tstsogoo** [pweingardt/mylyn-gitlab#49]
"Invalid path in host" error by clone repo like:  https://gitlab.com/demo/demo.git
Eclipse Oxygen.2 Release (4.7.2)

**Comment by PhilMFischer** [comment]
Please have a look to the ticket #47 .

There are three things at the Moment:
- GitLab abandoned it'sAPI v3 int he latest versions and recommends to use version 4. This connector still uses v3.
- The underlying java GitLab lib has recently been migrated to v4 but still contains a bug to be fixed, so it can be used here.
- Even though with all the fixes, I can't make the connector connect with user/password authentication, but app-token is working.

I am preparing a fix that I can provide, once the underlying GitLab jar has been fixed. Would be great if someone else could investigate the user/password issue.

**Comment by cvgaviao** [comment]
@PhilMFischer , could you share the steps you take to make this mylyn connect using app-token?

**Comment by pweingardt** [comment]
I need a more thorough example to test this issue...
Is it regarding a repository on gitlab.com? Is the issue already fixed with the new plugin version 2.1.0?

**Comment by geotom** [comment]
Have the same issue (Eclipse 2018-09, Linux, openjdk 10.0.2 2018-07-17) with Gitlab connector 2.1.0.
Steps taken: I create a new repository (Hosted on gitlab.com). If I use my user/password as credentials the validation fails with "Invalid path in host". If I use the access token (which worked in the past with APIv3), the validation process hangs & I cannot cancel it. See https://github.com/pweingardt/mylyn-gitlab/issues/47#issuecomment-430233563

**Comment by medeirosramos** [comment]
Have the same issue (Eclipse 2018-09).
@pweingardt the plugin version 2.1.0 not fixed. You can test with link https://gitlab.com/gitlab-org/release/tasks.git

**Comment by stolp** [comment]
The first problem here is, that the error message `Invalid path in host` hides the reason for this error, namely that the `/api/v4/issues` endpoint can not be found (HTTP 404).

This is due to a breaking change in the GitLab API introduced with GitLab 10.2 and above which dropped the ability for username/password authentication: [https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#private-tokens](https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#private-tokens)

So any attempt to authenticate with a private Token (username/password) **will not work** in recent GitLab releases.

It might be a god idea for the plugin UI to to either probe this condition and disable the default username/password authentication or switch the default authentication method to access tokens to avoid user confusion.

**Comment by geotom** [comment]
Any updates on this issue?
The README for 2.10 mentions:

> The new version 2.1.0 works with the Gitlab API v4, but you must recreate the repository in Mylyn, otherwise the issues can not be syncronized due to the changes in the Gitlab API v4.

But even when recreating the Mylyn repository I get the same "Invalid host" message. It's frustrating.

**Comment by stevieJ** [comment]
First, thanks for having a crack at this, a working issue synchronisation between Eclipse/Mylyn and GitLab would be very helpful.

**Current State**

1. I can connect to a self hosted GitLab repository using a GitLab Access token and validate the repository.
2. I can create an issue in Eclipse that is immediately seen & bidirectionally synchronised in GitLab
3. I can't see any issues created in GitLab within Eclipse. No query seems to pick them up.
4. The query hover-over always says 'Synchronised: \<never\>' 

Any thoughts?

**Environment**

* Arch Linux on Dell Precision 7530
* Eclipse 2019-03
* Mylyn-GitLab Connector 2.1.0
* OpenJDK Runtime 12.0.2+10
* GitLab Community Edition 10.5.2 b951e0d

**Comment by rrusch** [comment]
I see the same Issue as @stevieJ, but only on one project of our self hosted GitLab server.

- GitLab CE 12.3.1
- Eclipse 2019-09
- Mylyn-GitLab Connector 2.1.0

**Comment by rrusch** [comment]
> I see the same Issue as @stevieJ, but only on one project of our self hosted GitLab server.
> 
> * GitLab CE 12.3.1
> * Eclipse 2019-09
> * Mylyn-GitLab Connector 2.1.0

In my case, this was related to issue #54. Removed the due date from the issue and all tasks reappeared.
